//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace SheetData
{
	[Serializable]
	public class InterestRateLoanTable_Server : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private long _UID;
		public long UID { get { return _UID; } set{_UID=value; } }

		[SerializeField]
		private int _Year;
		public int Year { get { return _Year; } set{_Year=value; } }

		[SerializeField]
		private float _month1;
		public float month1 { get { return _month1; } set{_month1=value; } }

		[SerializeField]
		private float _month2;
		public float month2 { get { return _month2; } set{_month2=value; } }

		[SerializeField]
		private float _month3;
		public float month3 { get { return _month3; } set{_month3=value; } }

		[SerializeField]
		private float _month4;
		public float month4 { get { return _month4; } set{_month4=value; } }

		[SerializeField]
		private float _month5;
		public float month5 { get { return _month5; } set{_month5=value; } }

		[SerializeField]
		private float _month6;
		public float month6 { get { return _month6; } set{_month6=value; } }

		[SerializeField]
		private float _month7;
		public float month7 { get { return _month7; } set{_month7=value; } }

		[SerializeField]
		private float _month8;
		public float month8 { get { return _month8; } set{_month8=value; } }

		[SerializeField]
		private float _month9;
		public float month9 { get { return _month9; } set{_month9=value; } }

		[SerializeField]
		private float _month10;
		public float month10 { get { return _month10; } set{_month10=value; } }

		[SerializeField]
		private float _month11;
		public float month11 { get { return _month11; } set{_month11=value; } }

		[SerializeField]
		private float _month12;
		public float month12 { get { return _month12; } set{_month12=value; } }


		public InterestRateLoanTable_Server()
		{
		}

#if UNITY_EDITOR
		public InterestRateLoanTable_Server(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _UID);
			TryParse(sheet[row][column++], out _Year);
			TryParse(sheet[row][column++], out _month1);
			TryParse(sheet[row][column++], out _month2);
			TryParse(sheet[row][column++], out _month3);
			TryParse(sheet[row][column++], out _month4);
			TryParse(sheet[row][column++], out _month5);
			TryParse(sheet[row][column++], out _month6);
			TryParse(sheet[row][column++], out _month7);
			TryParse(sheet[row][column++], out _month8);
			TryParse(sheet[row][column++], out _month9);
			TryParse(sheet[row][column++], out _month10);
			TryParse(sheet[row][column++], out _month11);
			TryParse(sheet[row][column++], out _month12);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class InterestRateLoanTable_InterestRateLoanTable_Server : EERowDataCollection
	{
		
		public List<InterestRateLoanTable_Server> elements = new List<InterestRateLoanTable_Server>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as InterestRateLoanTable_Server);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
