//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace SheetData
{
	[Serializable]
	public class ItemDataTable_Client : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private long _UID;
		public long UID { get { return _UID; } set{_UID=value; } }

		[SerializeField]
		private string _CurrencyType;
		public string CurrencyType { get { return _CurrencyType; } set{_CurrencyType=value; } }

		[SerializeField]
		private int _ItemType;
		public int ItemType { get { return _ItemType; } set{_ItemType=value; } }

		[SerializeField]
		private int _ProductionRate;
		public int ProductionRate { get { return _ProductionRate; } set{_ProductionRate=value; } }

		[SerializeField]
		private int _ItemEquipType;
		public int ItemEquipType { get { return _ItemEquipType; } set{_ItemEquipType=value; } }

		[SerializeField]
		private int _IsStackType;
		public int IsStackType { get { return _IsStackType; } set{_IsStackType=value; } }

		[SerializeField]
		private int _StackMaxCount;
		public int StackMaxCount { get { return _StackMaxCount; } set{_StackMaxCount=value; } }

		[SerializeField]
		private int _DurabilityMaxValue;
		public int DurabilityMaxValue { get { return _DurabilityMaxValue; } set{_DurabilityMaxValue=value; } }

		[SerializeField]
		private int _DurabilityRegenValue;
		public int DurabilityRegenValue { get { return _DurabilityRegenValue; } set{_DurabilityRegenValue=value; } }

		[SerializeField]
		private int _DurabilityRegenTicTime;
		public int DurabilityRegenTicTime { get { return _DurabilityRegenTicTime; } set{_DurabilityRegenTicTime=value; } }

		[SerializeField]
		private int _IsDurabilityRepare;
		public int IsDurabilityRepare { get { return _IsDurabilityRepare; } set{_IsDurabilityRepare=value; } }

		[SerializeField]
		private int _DurabilityReparePrice;
		public int DurabilityReparePrice { get { return _DurabilityReparePrice; } set{_DurabilityReparePrice=value; } }

		[SerializeField]
		private int _DurabilityRepareValue;
		public int DurabilityRepareValue { get { return _DurabilityRepareValue; } set{_DurabilityRepareValue=value; } }

		[SerializeField]
		private int _DurabilityRepareTime;
		public int DurabilityRepareTime { get { return _DurabilityRepareTime; } set{_DurabilityRepareTime=value; } }

		[SerializeField]
		private int _UpgradeGroupId;
		public int UpgradeGroupId { get { return _UpgradeGroupId; } set{_UpgradeGroupId=value; } }

		[SerializeField]
		private int _PhysicalDamage;
		public int PhysicalDamage { get { return _PhysicalDamage; } set{_PhysicalDamage=value; } }

		[SerializeField]
		private int _PhysicalDefense;
		public int PhysicalDefense { get { return _PhysicalDefense; } set{_PhysicalDefense=value; } }

		[SerializeField]
		private int _AttackRange;
		public int AttackRange { get { return _AttackRange; } set{_AttackRange=value; } }

		[SerializeField]
		private int _AttackSpeed;
		public int AttackSpeed { get { return _AttackSpeed; } set{_AttackSpeed=value; } }

		[SerializeField]
		private int _MoveSpeed;
		public int MoveSpeed { get { return _MoveSpeed; } set{_MoveSpeed=value; } }

		[SerializeField]
		private int _Weight;
		public int Weight { get { return _Weight; } set{_Weight=value; } }

		[SerializeField]
		private int _OrignalBuyPrice;
		public int OrignalBuyPrice { get { return _OrignalBuyPrice; } set{_OrignalBuyPrice=value; } }

		[SerializeField]
		private int _OrignalSellPrice;
		public int OrignalSellPrice { get { return _OrignalSellPrice; } set{_OrignalSellPrice=value; } }

		[SerializeField]
		private int _DropEffectSoundId;
		public int DropEffectSoundId { get { return _DropEffectSoundId; } set{_DropEffectSoundId=value; } }

		[SerializeField]
		private int _SkillId;
		public int SkillId { get { return _SkillId; } set{_SkillId=value; } }

		[SerializeField]
		private int _ActorId;
		public int ActorId { get { return _ActorId; } set{_ActorId=value; } }

		[SerializeField]
		private int _IconId;
		public int IconId { get { return _IconId; } set{_IconId=value; } }

		[SerializeField]
		private string _AtlasName;
		public string AtlasName { get { return _AtlasName; } set{_AtlasName=value; } }

		[SerializeField]
		private string _SpriteName;
		public string SpriteName { get { return _SpriteName; } set{_SpriteName=value; } }

		[SerializeField]
		private string _Description;
		public string Description { get { return _Description; } set{_Description=value; } }


		public ItemDataTable_Client()
		{
		}

#if UNITY_EDITOR
		public ItemDataTable_Client(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _UID);
			TryParse(sheet[row][column++], out _CurrencyType);
			TryParse(sheet[row][column++], out _ItemType);
			TryParse(sheet[row][column++], out _ProductionRate);
			TryParse(sheet[row][column++], out _ItemEquipType);
			TryParse(sheet[row][column++], out _IsStackType);
			TryParse(sheet[row][column++], out _StackMaxCount);
			TryParse(sheet[row][column++], out _DurabilityMaxValue);
			TryParse(sheet[row][column++], out _DurabilityRegenValue);
			TryParse(sheet[row][column++], out _DurabilityRegenTicTime);
			TryParse(sheet[row][column++], out _IsDurabilityRepare);
			TryParse(sheet[row][column++], out _DurabilityReparePrice);
			TryParse(sheet[row][column++], out _DurabilityRepareValue);
			TryParse(sheet[row][column++], out _DurabilityRepareTime);
			TryParse(sheet[row][column++], out _UpgradeGroupId);
			TryParse(sheet[row][column++], out _PhysicalDamage);
			TryParse(sheet[row][column++], out _PhysicalDefense);
			TryParse(sheet[row][column++], out _AttackRange);
			TryParse(sheet[row][column++], out _AttackSpeed);
			TryParse(sheet[row][column++], out _MoveSpeed);
			TryParse(sheet[row][column++], out _Weight);
			TryParse(sheet[row][column++], out _OrignalBuyPrice);
			TryParse(sheet[row][column++], out _OrignalSellPrice);
			TryParse(sheet[row][column++], out _DropEffectSoundId);
			TryParse(sheet[row][column++], out _SkillId);
			TryParse(sheet[row][column++], out _ActorId);
			TryParse(sheet[row][column++], out _IconId);
			TryParse(sheet[row][column++], out _AtlasName);
			TryParse(sheet[row][column++], out _SpriteName);
			TryParse(sheet[row][column++], out _Description);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class ItemDataTable_ItemDataTable_Client : EERowDataCollection
	{
		
		public List<ItemDataTable_Client> elements = new List<ItemDataTable_Client>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as ItemDataTable_Client);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

	
public List<ItemDataTable_Client> OnGetAllData()
		{		
return elements;
		}		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
