//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace SheetData
{
	[Serializable]
	public class ItemPriceRateTable_Server : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private long _UID;
		public long UID { get { return _UID; } set{_UID=value; } }

		[SerializeField]
		private int _Year;
		public int Year { get { return _Year; } set{_Year=value; } }

		[SerializeField]
		private float _Jan;
		public float Jan { get { return _Jan; } set{_Jan=value; } }

		[SerializeField]
		private float _Feb;
		public float Feb { get { return _Feb; } set{_Feb=value; } }

		[SerializeField]
		private float _Mar;
		public float Mar { get { return _Mar; } set{_Mar=value; } }

		[SerializeField]
		private float _Apr;
		public float Apr { get { return _Apr; } set{_Apr=value; } }

		[SerializeField]
		private float _May;
		public float May { get { return _May; } set{_May=value; } }

		[SerializeField]
		private float _Jun;
		public float Jun { get { return _Jun; } set{_Jun=value; } }

		[SerializeField]
		private float _Jul;
		public float Jul { get { return _Jul; } set{_Jul=value; } }

		[SerializeField]
		private float _Aug;
		public float Aug { get { return _Aug; } set{_Aug=value; } }

		[SerializeField]
		private float _Sep;
		public float Sep { get { return _Sep; } set{_Sep=value; } }

		[SerializeField]
		private float _Oct;
		public float Oct { get { return _Oct; } set{_Oct=value; } }

		[SerializeField]
		private float _Nov;
		public float Nov { get { return _Nov; } set{_Nov=value; } }

		[SerializeField]
		private float _Dec;
		public float Dec { get { return _Dec; } set{_Dec=value; } }


		public ItemPriceRateTable_Server()
		{
		}

#if UNITY_EDITOR
		public ItemPriceRateTable_Server(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _UID);
			TryParse(sheet[row][column++], out _Year);
			TryParse(sheet[row][column++], out _Jan);
			TryParse(sheet[row][column++], out _Feb);
			TryParse(sheet[row][column++], out _Mar);
			TryParse(sheet[row][column++], out _Apr);
			TryParse(sheet[row][column++], out _May);
			TryParse(sheet[row][column++], out _Jun);
			TryParse(sheet[row][column++], out _Jul);
			TryParse(sheet[row][column++], out _Aug);
			TryParse(sheet[row][column++], out _Sep);
			TryParse(sheet[row][column++], out _Oct);
			TryParse(sheet[row][column++], out _Nov);
			TryParse(sheet[row][column++], out _Dec);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class ItemPriceRateTable_ItemPriceRateTable_Server : EERowDataCollection
	{
		
		public List<ItemPriceRateTable_Server> elements = new List<ItemPriceRateTable_Server>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as ItemPriceRateTable_Server);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
